### PR TITLE
Use intra-doc links and backticks.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by pczarn** [comment]
I would prefer if you did fragment specifiers. Example:

```rust
/// This is foobar implementation of [`union_with`].
///
/// [`union_with`]: Self::union_with
struct MySpecialFormatter;
```

**Comment by pczarn** [comment]
I guess I am asking for additional stuff; I can do this myself. Merging.

**Comment by waywardmonkeys** [comment]
I was going to do still today (was out at dinner earlier). Thanks though!

**Comment by pczarn** [comment]
@waywardmonkeys Feel free to do fragment specifiers. Would you like to add these changes to `bit-vec` too?

**Comment by waywardmonkeys** [comment]
Sure! Probably this weekend.

**Pull request merged**
