### PR TITLE
Add serde support

### PR DESCRIPTION
**Pull request by LizzyFleckenstein03**

### CODE REVIEW

**Comment by Gankra** [comment]
serde2..? huh..? (oh I see, trying to make "serde" the interface for flipping this on, and not "serde-impl" or whatever)

**Comment by Gankra** [comment]
This implementation seems incorrect. A BitSet is equivalent to a `BTreeSet<usize>`, the thing you serialize/deserialize should be the indices that contain a "1" in the BitVec (which is e.g. what the iterator yields).

**Review by Gankra — CHANGES_REQUESTED** [review]
(so this needs to be reworked)

**Comment by pczarn** [comment]
This needs some rework.

**Pull request closed without merging**
